Repository Evgenii-Bazhaov/Hacktoberfest2024-25, pull requests merged in 2024-10, with the labels that each got.

#1 Models added of mini project
  comment.models.js
  post.models.js
  user.models.js
Labels: enhancement, good first issue, hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#4 updated Ai Quotes Generator
  Ai Quotes Generator/styles.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#5 Create index.js for Quotes Generator
  Ai Quotes Generator/index.js
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#6 Added script.js
  Ai Quotes Generator/script.js
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#7 added my project
  Rock-Paper-Scissors/RPSgame.css
  Rock-Paper-Scissors/RPSgame.html
  Rock-Paper-Scissors/RPSgame.js
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#10 Add simple canvas text project
  SimpleCanvasText/app.js
  SimpleCanvasText/index.html
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#9 added a calculator project
  Calculator/Calculator.css
  Calculator/Calculator.html
  Calculator/Calculator.js
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#11 adding stopwatch
  stopwatch/stopwatch.css
  stopwatch/stopwatch.html
  stopwatch/stopwatch.js
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#14 Memory block game added
  Memory Block/Assests/CSS/style.css
  Memory Block/Assests/Images/brainstorm.png
  Memory Block/Assests/JavaScript/script.js
  Memory Block/index.html
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#16 Created tic-tac-toe game
  Tic-Tac_Toe game/.gitignore
  Tic-Tac_Toe game/README.md
  Tic-Tac_Toe game/eslint.config.js
  Tic-Tac_Toe game/index.html
  Tic-Tac_Toe game/package-lock.json
  Tic-Tac_Toe game/package.json
  Tic-Tac_Toe game/postcss.config.js
  Tic-Tac_Toe game/public/vite.svg
  Tic-Tac_Toe game/src/App.css
  Tic-Tac_Toe game/src/App.jsx
  Tic-Tac_Toe game/src/assets/react.svg
  Tic-Tac_Toe game/src/index.css
  Tic-Tac_Toe game/src/main.jsx
  Tic-Tac_Toe game/tailwind.config.js
  Tic-Tac_Toe game/vite.config.js
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#17 Added truth or dare game
  Truth-or-Dare/index.html
  Truth-or-Dare/script.js
  Truth-or-Dare/style.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#22 Temperature Converter
  Temperature Converter
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#20 Eyes Follow the cursor mini project added
  Eyes Follow Cursor/index.html
  Eyes Follow Cursor/script.js
  Eyes Follow Cursor/style.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#18 Added program for word guess game in Python
  Word Guess Game/game.py
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#28 added word guessing game in js
  wordguessing/index.html
  wordguessing/script.js
  wordguessing/style.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#24 Create a QR code generator for texts and links
  QR code generator/.gitignore
  QR code generator/README.md
  QR code generator/eslint.config.js
  QR code generator/index.html
  QR code generator/package-lock.json
  QR code generator/package.json
  QR code generator/postcss.config.js
  QR code generator/public/vite.svg
  QR code generator/src/App.css
  QR code generator/src/App.jsx
  QR code generator/src/assets/react.svg
  QR code generator/src/components/QrCodeGenerator.jsx
  QR code generator/src/index.css
  QR code generator/src/main.jsx
  QR code generator/tailwind.config.js
  QR code generator/vite.config.js
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#29 Added Meme Generator
  Meme Generator/index.html
  Meme Generator/script.js
  Meme Generator/style.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest, gssoc-ext, gsooc

#33 Created weather app using react.js
  WeatherApp/.gitignore
  WeatherApp/README.md
  WeatherApp/eslint.config.js
  WeatherApp/index.html
  WeatherApp/package-lock.json
  WeatherApp/package.json
  WeatherApp/postcss.config.js
  WeatherApp/public/vite.svg
  WeatherApp/src/App.css
  WeatherApp/src/App.jsx
  WeatherApp/src/assets/react.svg
  WeatherApp/src/components/CurrentDateInsight.jsx
  WeatherApp/src/components/DayForecast.jsx
  WeatherApp/src/components/FiveDayForecast.jsx
  WeatherApp/src/components/Navbar.jsx
  WeatherApp/src/components/TemperatureDetails.jsx
  WeatherApp/src/components/ToggleButtonIcon.jsx
  WeatherApp/src/index.css
  WeatherApp/src/main.jsx
  WeatherApp/src/pages/CityPage.jsx
  WeatherApp/src/pages/HomePage.jsx
  WeatherApp/src/redux/store.js
  WeatherApp/src/redux/weatherSlice.js
  WeatherApp/tailwind.config.js
  WeatherApp/vite.config.js
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#36 Create Neumorphic_calculator.css
  Calculator/Neumorphic_calculator.css
Labels: enhancement, hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#38 Feat : card game #10
  cardGame/cardGame.html
  cardGame/script.js
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#41 Issue #30 solved
  Card Match Game/cardGame.html
  Card Match Game/script.js
  book store/backend/.gitignore
  book store/backend/index.js
  book store/backend/package-lock.json
  book store/backend/package.json
  book store/book-manager/.gitignore
  book store/book-manager/README.md
  book store/book-manager/package-lock.json
  book store/book-manager/package.json
  book store/book-manager/public/favicon.ico
  book store/book-manager/public/index.html
  book store/book-manager/public/logo192.png
  book store/book-manager/public/logo512.png
  book store/book-manager/public/manifest.json
  book store/book-manager/public/robots.txt
  book store/book-manager/src/App.css
  book store/book-manager/src/App.js
  book store/book-manager/src/App.test.js
  book store/book-manager/src/components/AddBook.css
  book store/book-manager/src/components/AddBook.js
  book store/book-manager/src/components/BookList.css
  book store/book-manager/src/components/BookList.js
  book store/book-manager/src/components/Home.css
  book store/book-manager/src/components/Home.js
  book store/book-manager/src/components/UpdateBook.js
  book store/book-manager/src/index.css
  book store/book-manager/src/index.js
  book store/book-manager/src/logo.svg
  book store/book-manager/src/reportWebVitals.js
  book store/book-manager/src/setupTests.js
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#44 Analog clock added
  Analog Clock/index.html
  Analog Clock/script.js
  Analog Clock/style.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest, gssoc-ext, gsooc

#46 created a single person retro space shooter game
  Space_shooter_game/game.js
  Space_shooter_game/index.html
  Space_shooter_game/style.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#48 Added 2048 game
  2048/index.html
  2048/script.js
  2048/style.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#49 Add Interactive Infinity Maze game with dynamic wall behavior and navigation
  Interactive Infinity Maze/index.html
  Interactive Infinity Maze/script.js
  Interactive Infinity Maze/style.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#54 Bounce-Nokia Game Clone
  Bounce-Nokia-Clone-main/README.md
  Bounce-Nokia-Clone-main/assets/bg/bg.jpg
  Bounce-Nokia-Clone-main/assets/bg/level-select.png
  Bounce-Nokia-Clone-main/assets/fonts/YanoneKaffeesatz-Bold.ttf
  Bounce-Nokia-Clone-main/assets/fonts/YanoneKaffeesatz-Regular.ttf
  Bounce-Nokia-Clone-main/assets/tile/ball_small.png
  Bounce-Nokia-Clone-main/assets/tile/button_menu.png
  Bounce-Nokia-Clone-main/assets/tile/button_next.png
  Bounce-Nokia-Clone-main/assets/tile/button_retry.png
  Bounce-Nokia-Clone-main/assets/tile/crown.png
  Bounce-Nokia-Clone-main/assets/tile/failed_title.png
  Bounce-Nokia-Clone-main/assets/tile/gbar_life.png
  Bounce-Nokia-Clone-main/assets/tile/gbar_ring.png
  Bounce-Nokia-Clone-main/assets/tile/lselect_keylock.png
  Bounce-Nokia-Clone-main/assets/tile/lselect_level.png
  Bounce-Nokia-Clone-main/assets/tile/lselect_level_locked.png
  Bounce-Nokia-Clone-main/assets/tile/lselect_star.png
  Bounce-Nokia-Clone-main/assets/tile/lselect_star_grey.png
  Bounce-Nokia-Clone-main/assets/tile/menu_button_play.png
  Bounce-Nokia-Clone-main/assets/tile/menu_logo.png
  Bounce-Nokia-Clone-main/assets/tile/small_button_retry.png
  Bounce-Nokia-Clone-main/assets/tile/spritesheet.png
  Bounce-Nokia-Clone-main/assets/tile/star_gray.png
  Bounce-Nokia-Clone-main/assets/tile/star_yellow.png
  Bounce-Nokia-Clone-main/index.html
  Bounce-Nokia-Clone-main/js/canvas.js
  Bounce-Nokia-Clone-main/js/enemy.js
  Bounce-Nokia-Clone-main/js/entity.js
  Bounce-Nokia-Clone-main/js/game.js
  Bounce-Nokia-Clone-main/js/input.js
  Bounce-Nokia-Clone-main/js/level.js
  Bounce-Nokia-Clone-main/js/main.js
  Bounce-Nokia-Clone-main/js/map.js
  Bounce-Nokia-Clone-main/js/player.js
  Bounce-Nokia-Clone-main/js/sprite.js
  Bounce-Nokia-Clone-main/js/tile.js
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#50 Theme Changer
  Theme/package-lock.json
  Theme/public/favicon.ico
  Theme/public/index.html
  Theme/public/logo192.png
  Theme/public/logo512.png
  Theme/public/manifest.json
  Theme/public/robots.txt
  Theme/src/App.css
  Theme/src/App.js
  Theme/src/Change.jsx
  Theme/src/SearchBar.jsx
  Theme/src/Theme.js
  Theme/src/index.css
  Theme/src/index.js
  Theme/tailwind.config.js
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#63 Add Color Matching Game
  color-matching-game/.gitignore
  color-matching-game/README.md
  color-matching-game/package-lock.json
  color-matching-game/package.json
  color-matching-game/public/favicon.ico
  color-matching-game/public/index.html
  color-matching-game/public/logo192.png
  color-matching-game/public/logo512.png
  color-matching-game/public/manifest.json
  color-matching-game/public/robots.txt
  color-matching-game/src/App.js
  color-matching-game/src/App.test.js
  color-matching-game/src/ColorMatchingGame.jsx
  color-matching-game/src/components/ui/Alert.js
  color-matching-game/src/index.css
  color-matching-game/src/index.js
  color-matching-game/src/logo.svg
  color-matching-game/src/reportWebVitals.js
  color-matching-game/src/setupTests.js
  color-matching-game/tailwind.config.js
  snake-game/.gitignore
  snake-game/README.md
  snake-game/package-lock.json
  snake-game/package.json
  snake-game/public/favicon.ico
  snake-game/public/index.html
  snake-game/public/logo192.png
  snake-game/public/logo512.png
  snake-game/public/manifest.json
  snake-game/public/robots.txt
  snake-game/src/App.css
  snake-game/src/App.js
  snake-game/src/App.test.js
  snake-game/src/index.css
  snake-game/src/index.js
  snake-game/src/logo.svg
  snake-game/src/reportWebVitals.js
  snake-game/src/setupTests.js
  snake-game/tailwind.config.js
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#56 Added my BMI calculator project
  BMICalculator/index.css
  BMICalculator/index.html
  BMICalculator/index.js
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#55 Added a simple wordle game implementation
  wordle/index.html
  wordle/script.js
  wordle/style.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#73 Add files via upload
  Kd-Trees/Kd-Trees-master/KdTree.java
  Kd-Trees/Kd-Trees-master/PointSET.java
  Kd-Trees/Kd-Trees-master/README.md
  Kd-Trees/Kd-Trees-master/images/Screenshot (16).png
  Kd-Trees/Kd-Trees-master/images/Screenshot (17).png
  Kd-Trees/Kd-Trees-master/images/Screenshot (18).png
  Kd-Trees/Kd-Trees-master/images/Screenshot (19).png
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#72 Amazon clone
  Amazon Clone/box1_image (1).jpg
  Amazon Clone/box2_image.jpg
  Amazon Clone/box3_image.jpg
  Amazon Clone/box4_image.jpg
  Amazon Clone/box5_image.jpg
  Amazon Clone/box6_image.jpg
  Amazon Clone/box7_image.jpg
  Amazon Clone/box8_image.jpg
  Amazon Clone/hero_image.jpg
  Amazon Clone/index.html
  Amazon Clone/style.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#87 Enhanced basic calculator
  Calculator/Enhanced basic calculator
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#83 Star Catcher Adventure
  Star Catcher Adventure/index.html
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#82 Added The Color Picker project
  color-picker/.gitignore
  color-picker/README.md
  color-picker/index.html
  color-picker/script.js
  color-picker/style.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#81 Add mouse listener on the canvas element
  SimpleCanvasText/app.js
  SimpleCanvasText/index.html
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#79 Password Generator using Html Css and Js.
  Password-Generator/index.html
  Password-Generator/script.js
  Password-Generator/style.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#102 Temperature converter App
  Temperature-Converter/index.html
  Temperature-Converter/script.js
  Temperature-Converter/styles.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#100 Added Student Database Management System
  StudentDatabaseSystem/.gitignore
  StudentDatabaseSystem/README.md
  StudentDatabaseSystem/main.py
  StudentDatabaseSystem/requirements.txt
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#116 Redux
  Redux/package-lock.json
  Redux/public/favicon.ico
  Redux/public/index.html
  Redux/public/logo192.png
  Redux/public/logo512.png
  Redux/public/manifest.json
  Redux/public/robots.txt
  Redux/src/App.css
  Redux/src/App.js
  Redux/src/app/store.js
  Redux/src/components/AddTodoForm.jsx
  Redux/src/components/TodoList.jsx
  Redux/src/features/reducer.js
  Redux/src/index.css
  Redux/src/index.js
  Redux/src/logo.svg
  Redux/src/reportWebVitals.js
  Redux/src/setupTests.js
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#154 Condtional Rendering
  Condtional Rendering/1-multiple-returns.js
  Condtional Rendering/2-short-circuit.js
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#146 Add Faulty Calculator Issue #133
  Faulty-Calculator/README.md
  Faulty-Calculator/index.html
  Faulty-Calculator/index.js
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#132 Create Fidget.Spinner.py
  .idea/Fidget.Spinner.py
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#131 Create Caterpillar.game.py
  .idea/Caterpillar.game.py
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#157 Hello World #147
  HelloWorld.c
  hello_world.clj
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#193 added currency converter website
  currency_converter/index.html
  currency_converter/script.js
  currency_converter/script1.js
  currency_converter/style.css
  currency_converter/temp
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#181 Progress Step App
  Progress steps/index.html
  Progress steps/readme.md
  Progress steps/script.js
  Progress steps/style.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#189 Add Whack-a-Mole Game Code
  Whack-a-Mole Game/index.html
  Whack-a-Mole Game/script.js
  Whack-a-Mole Game/styles.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#256 Adding linear and binary search in python
  Searching.py
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#251 [Feature] Cyclic redundancy check in java added!
  Cyclic-redundancy-check/Crc.java
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#252 added a music-player-app
  MusicPlayer/index.html
  MusicPlayer/main.js
  MusicPlayer/style.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#253 Number Guessing Game with Clues
  Number Guessing/index.html
  Number Guessing/script.js
  Number Guessing/style.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#254 added internet speed checker website
  internet_speed_checker/images.png
  internet_speed_checker/index.html
  internet_speed_checker/script.js
  internet_speed_checker/style.css
  internet_speed_checker/temp
  internet_speed_checker/temp1
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#255 Finance Manager
  Webpage 5/index.html
  Webpage 5/script.js
  Webpage 5/styles.css
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest, gssoc-ext, gsooc

#185 Netflix ui clone
  Netflix ui clone
Labels: enhancement, hacktoberfest2024, hacktoberfest, change

#187 Create Password generator in html css js
  Password generator in html css js
Labels: enhancement, hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest, change

#278 Added Password Strength Checker
  Password Strength Checker/img.jpg
  Password Strength Checker/index.html
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest

#279 Added Age Calculator
  AgeInYearsMonthsDays/Age_Calculator.py
Labels: hacktoberfest-accepted, hacktoberfest2024, hacktoberfest-approved, hacktoberfest
